# Generated by Django 4.1.1 on 2022-09-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_product_person_of_profile_quntity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
